ALTER TABLE REG_LOG MODIFY COLUMN REG_USER_ID VARCHAR(255) NOT NULL;
ALTER TABLE REG_COMMENT MODIFY COLUMN REG_USER_ID VARCHAR(255) NOT NULL;
ALTER TABLE REG_RATING MODIFY COLUMN REG_USER_ID VARCHAR(255) NOT NULL;
ALTER TABLE REG_TAG MODIFY COLUMN REG_USER_ID VARCHAR(255) NOT NULL;

ALTER TABLE REG_RESOURCE MODIFY COLUMN REG_CREATOR VARCHAR(255) NOT NULL;
ALTER TABLE REG_RESOURCE MODIFY COLUMN REG_LAST_UPDATOR VARCHAR(255) NOT NULL;

ALTER TABLE REG_RESOURCE_HISTORY MODIFY COLUMN REG_CREATOR VARCHAR(255) NOT NULL;
ALTER TABLE REG_RESOURCE_HISTORY MODIFY COLUMN REG_LAST_UPDATOR VARCHAR(255) NOT NULL;
