ALTER TABLE REG_LOG MODIFY (REG_USER_ID VARCHAR(255))
/
ALTER TABLE REG_COMMENT MODIFY (REG_USER_ID VARCHAR(255))
/
ALTER TABLE REG_RATING MODIFY (REG_USER_ID VARCHAR(255))
/
ALTER TABLE REG_TAG MODIFY (REG_USER_ID VARCHAR(255))
/
ALTER TABLE REG_RESOURCE MODIFY (REG_CREATOR VARCHAR(255))
/
ALTER TABLE REG_RESOURCE MODIFY (REG_LAST_UPDATOR VARCHAR(255))
/
ALTER TABLE REG_RESOURCE_HISTORY MODIFY (REG_CREATOR VARCHAR(255))
/
ALTER TABLE REG_RESOURCE_HISTORY MODIFY (REG_LAST_UPDATOR VARCHAR(255))
/
