ALTER TABLE REG_LOG ALTER COLUMN REG_USER_ID VARCHAR(255) NOT NULL;
ALTER TABLE REG_COMMENT ALTER COLUMN REG_USER_ID VARCHAR(255) NOT NULL;
ALTER TABLE REG_RATING ALTER COLUMN REG_USER_ID VARCHAR(255) NOT NULL;
ALTER TABLE REG_TAG ALTER COLUMN REG_USER_ID VARCHAR(255) NOT NULL;

ALTER TABLE REG_RESOURCE ALTER COLUMN REG_CREATOR VARCHAR(255) NOT NULL;
ALTER TABLE REG_RESOURCE ALTER COLUMN REG_LAST_UPDATOR VARCHAR(255) NOT NULL;

ALTER TABLE REG_RESOURCE_HISTORY ALTER COLUMN REG_CREATOR VARCHAR(255) NOT NULL;
ALTER TABLE REG_RESOURCE_HISTORY ALTER COLUMN REG_LAST_UPDATOR VARCHAR(255) NOT NULL;
