ALTER TABLE REG_LOG ALTER COLUMN REG_USER_ID TYPE VARCHAR(255);
ALTER TABLE REG_LOG ALTER COLUMN REG_USER_ID SET NOT NULL;

ALTER TABLE REG_COMMENT ALTER COLUMN REG_USER_ID TYPE VARCHAR(255);
ALTER TABLE REG_COMMENT ALTER COLUMN REG_USER_ID SET NOT NULL;

ALTER TABLE REG_RATING ALTER COLUMN REG_USER_ID TYPE VARCHAR(255);
ALTER TABLE REG_RATING ALTER COLUMN REG_USER_ID SET NOT NULL;

ALTER TABLE REG_TAG ALTER COLUMN REG_USER_ID TYPE VARCHAR(255);
ALTER TABLE REG_TAG ALTER COLUMN REG_USER_ID SET NOT NULL;

ALTER TABLE REG_RESOURCE ALTER COLUMN REG_CREATOR TYPE VARCHAR(255);
ALTER TABLE REG_RESOURCE ALTER COLUMN REG_CREATOR SET NOT NULL;

ALTER TABLE REG_RESOURCE ALTER COLUMN REG_LAST_UPDATOR TYPE VARCHAR(255);
ALTER TABLE REG_RESOURCE ALTER COLUMN REG_LAST_UPDATOR SET NOT NULL;

ALTER TABLE REG_RESOURCE_HISTORY ALTER COLUMN REG_CREATOR TYPE VARCHAR(255);
ALTER TABLE REG_RESOURCE_HISTORY ALTER COLUMN REG_CREATOR SET NOT NULL;

ALTER TABLE REG_RESOURCE_HISTORY ALTER COLUMN REG_LAST_UPDATOR TYPE VARCHAR(255);
ALTER TABLE REG_RESOURCE_HISTORY ALTER COLUMN REG_LAST_UPDATOR SET NOT NULL;
